# ############################################################################
# Model: Transformer LM of E2E ASR
# Tokens: unigram
# losses: NLL
# Training: Librispeech 960h transcript + LM corpus
# Authors:  Jianyuan Zhong 2021
# ############################################################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 2224
__set_seed: !apply:torch.manual_seed [!ref <seed>]
output_folder: !ref exp/LM/parl_30M_RNN-A/<seed>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
num_units: 1750
tokenizer_path: !ref exp/spm-full-with-specials2/spm.<num_units>.model
tokenizer: !new:sentencepiece.SentencePieceProcessor
    model_file: !ref <tokenizer_path>

# LM Data:
train_data: kaldi-s5/data/lm_parl_30M_corpus/plain_text
valid_data: kaldi-s5/data/lm_parl_30M_corpus/plain_text.valid

# Training parameters
dynbatch_kwargs:
    len_key: "tokens_eos"
    sampler_kwargs:
        target_batch_numel: 320
        max_batch_numel: 400

accu_steps: 1 # Gradient accumulation to simulate large batch training

number_of_epochs: 100
#batch_size: 80
lr: 0.001
ckpt_interval_minutes: -1 # save checkpoint every N min

# Dataloader options
train_dataloader_opts:
    batch_size: null
    pin_memory: False
    num_workers: 1
    looped_nominal_epoch: 20000
    persistent_workers: True

valid_dataloader_opts:
    batch_size: 1

test_dataloader_opts:
    batch_size: 1

# Outputs
pad_index: 0
blank_index: 1
unk_index: 1
bos_index: 1
eos_index: 1


# Model parameters
emb_size: 128
activation: !name:torch.nn.LeakyReLU
dropout: 0.0
rnn_layers: 2
rnn_neurons: 2048
dnn_blocks: 1
dnn_neurons: 512

# Outputs
output_neurons: !ref <num_units>

# Functions
model: !new:speechbrain.lobes.models.RNNLM.RNNLM
    output_neurons: !ref <output_neurons>
    embedding_dim: !ref <emb_size>
    activation: !ref <activation>
    dropout: !ref <dropout>
    rnn_layers: !ref <rnn_layers>
    rnn_neurons: !ref <rnn_neurons>
    dnn_blocks: !ref <dnn_blocks>
    dnn_neurons: !ref <dnn_neurons>

modules:
    model: !ref <model>

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

optimizer: !name:torch.optim.Adam
    lr: !ref <lr>
    betas: (0.9, 0.98)
    eps: 0.000000001

lr_annealing: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: 0.0025
    annealing_factor: 0.8
    patient: 0

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

compute_cost: !name:speechbrain.nnet.losses.nll_loss

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        scheduler: !ref <lr_annealing>
        counter: !ref <epoch_counter>
