# ############################################################################
# Model: Transformer LM of E2E ASR
# Tokens: unigram
# losses: NLL
# Training: Librispeech 960h transcript + LM corpus
# Authors:  Jianyuan Zhong 2021
# ############################################################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 2224
__set_seed: !apply:torch.manual_seed [!ref <seed>]
output_folder: !ref exp/LM/parl_30M_Trafo-D/<seed>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
num_units: 1750
tokenizer_path: !ref exp/spm-full-with-specials/spm.<num_units>.model
tokenizer: !new:sentencepiece.SentencePieceProcessor
    model_file: !ref <tokenizer_path>

# LM Data:
train_data: kaldi-s5/data/lm_parl_30M_corpus/plain_text
valid_data: kaldi-s5/data/lm_parl_30M_corpus/plain_text.valid

# Training parameters
number_of_epochs: 200
dynbatch_kwargs:
    len_key: "tokens_eos"
    sampler_kwargs:
        target_batch_numel: 320
        max_batch_numel: 400

lr: 1.
accu_steps: 4 # Gradient accumulation to simulate large batch training
ckpt_interval_minutes: -1 # save checkpoint every N min

# Dataloader options
train_dataloader_opts:
    batch_size: null
    pin_memory: False
    num_workers: 1
    looped_nominal_epoch: 20000
    persistent_workers: True

valid_dataloader_opts:
    batch_size: 1

test_dataloader_opts:
    batch_size: 1

# Outputs
pad_index: 0
blank_index: 1
unk_index: 1
bos_index: 2
eos_index: 3

# model params
d_model: 768

# Functions
model: !new:speechbrain.lobes.models.transformer.TransformerLM.TransformerLM  # yamllint disable-line rule:line-length
    vocab: !ref <num_units>
    d_model: !ref <d_model>
    nhead: 12
    num_encoder_layers: 12
    num_decoder_layers: 0
    d_ffn: 3072
    dropout: 0.0
    activation: !name:torch.nn.GELU
    normalize_before: False

modules:
    model: !ref <model>

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

optimizer: !name:torch.optim.Adam
    lr: 0
    betas: (0.9, 0.98)
    eps: 0.000000001

lr_annealing: !new:speechbrain.nnet.schedulers.NoamScheduler
    lr_initial: !ref <lr>
    n_warmup_steps: 250000
    model_size: !ref <d_model>

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

compute_cost: !name:speechbrain.nnet.losses.nll_loss

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        scheduler: !ref <lr_annealing>
        counter: !ref <epoch_counter>
